### PR TITLE
Updating the IaaM dates

### PR DESCRIPTION
**Pull request by stroebitzer**
sorry, too late for yesterdays plauscherl  ;)

### CODE REVIEW

**Comment by ddprrt** [comment]
I can't see a change :D 
What has happened?

**Comment by stroebitzer** [comment]
Hmmm. I wanted to add
```yaml
   -
      name: "Infrastructure as a Meetup 9"
      location: karriere.at
      date: 2019-07-03
      link: https://www.meetup.com/iaam-linz/events/262259179/
```
and had a merge conflict and probably made some mistake.

As it looks the change is already in https://github.com/technologieplauscherl/technologieplauscherl.github.io/edit/master/_data/community.yml

**Comment by ddprrt** [comment]
Yeah, I added this yesterday :-)

**Comment by stroebitzer** [comment]
Thx Man, you are truly a Batman   ;)

**Pull request closed without merging**
