### PR TITLE
Propose "Communicate efficiently with Software Architecture Diagrams" for #77

### PR DESCRIPTION
**Pull request by lasssim**
Hi,

I'd like to give a talk at the next Plauscherl.

This is the abstract:

> The ultimate goal of any software is to offer a great experience to its users. User interfaces and workflows must be clear, self-explanatory, and appealing. 
> 
> Software documentation should have a similar goal. Comprehensive diagrams that visualize ideas and concepts clearly are mandatory to do that. 
> 
> I am going to show how to create beautiful diagrams with the right level of detail, to communicate efficiently with other software professionals and stakeholders.

Do you already have a date for the next Plauscherl?

Br, Simon

### CODE REVIEW

**Comment by saxx** [comment]
Hallo Simon,

thanks a lot for your PR.

The next Plauscherl is going to be in October (probably the 5th of October) at Dynatrace. There's actually one speaker slot left - would you like to take this slot?

**Comment by lasssim** [comment]
This date works perfectly for me, I'd be happy do take the slot.

**Comment by saxx** [comment]
Great, consider it done :) @ddprrt as our "Dyntrace Liaison" still needs to announce the next Plauscherl on the website, but I already added your talk to our internal board, so you Liason consider it fixed :)

**Comment by lasssim** [comment]
perfect :) let me know if you need anything else from me.

**Comment by ddprrt** [comment]
5.10. it is, you still up?

**Comment by lasssim** [comment]
yes :)

**Comment by ddprrt** [comment]
🙌

**Pull request closed without merging**
